### PR TITLE
Add ScpCommand

### PR DESCRIPTION
**Pull request by alanjcfs**
I don't know if this will be useful, but I noticed that gaptool-client required "net/scp" without using it.

I added something to allow one to copy a local file to remote or vice versa.

### CODE REVIEW

**Comment by zeroed** [comment]
Thanks @alanjcfs !
:yum: 

Actually I'm not moving files back 'n' forth (with great power comes great responsibility :japanese_goblin:) ... Let's just think about some _security matters_ with @gbagnoli ...

**Comment by gbagnoli** [comment]
@alanjcfs Thanks!! Much appreciated, this is something that can be helpful and has been requested in the past.

Two things though: 

* I'm wondering if we can use arguments instead of option to avoid the need for  the `-v` flag which IMHO is hard to remember. Something like `gt scp -r role -e env -i inst local :remote` that can be reversed as
`gt scp -r role -e env -i inst :remote local`
* Add the option to copy the file to all (remote) machines. This can be a switch, and only support from local to remote (to ease the interface mostly), i.e. `gt ssh -r role -e env --all local :remote`

What do you think?

**Comment by alanjcfs** [comment]
I was using a task that exports a json file and wanted a way to download from remote to local (not from local to remote), so my thinking is to allow only downloading from remote to local (and not allowing local to remote), which is why I added the "toremote" flag for people who might want to copy something to the server. Do people want to copy files from local to remote? It seems unnecessary as using the deploy script should be enough.

**Comment by jfelectron** [comment]
Remote to local is more common than local to remote for us. You can also
always use s3cmd to push and pull files.

On Fri, Oct 23, 2015 at 10:43 AM, Alan Fung-Schwarz <
notifications@github.com> wrote:

> I was using a task that exports a json file and wanted a way to download
> from remote to local (not from local to remote), so my thinking is to allow
> only downloading from remote to local (and not allowing local to remote),
> which is why I added the "toremote" flag for people who might want to copy
> something to the server. Do people want to copy files from local to remote?
> It seems unnecessary as using the deploy script should be enough.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gild/gaptool-client/pull/9#issuecomment-150643630>.
>



-- 
*__________________*
*Jonathan Foley*
VP of Science| Gild, Inc.
800-664-2366  | *cell 510-725-8484*

465 California Street, Suite 1200
San Francisco, CA 94104
www.gild.com

**Comment by gbagnoli** [comment]
@alanjcfs I've re-implemented this command in https://github.com/Gild/gaptool-client/pull/10.
(commit: https://github.com/Gild/gaptool-client/commit/3ae65a7ca218aa3406a61a9a4ba7459289d20a4d)
Sorry for the double work, but having rewritten the backend to use SSHKit I had to touch all ssh-related command, this one included.

I'm gonna close this PR as the other one will be merged soon and the 0.8.x series is based on that one.
Giacomo

**Pull request closed without merging**
